CREATE TABLE IF NOT EXISTS users
 (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 username CHAR(20) NOT NULL,
 fullname CHAR(20) NOT NULL,
 phone CHAR(20) NOT NULL,
 address CHAR(40) NOT NULL,
 password CHAR(20) NOT NULL);